version: '2'

services:
  # TODO: change this name to match the name of your app
  expressjs-template:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    ports:
      # TODO: change this mapping to map the port your application listens on
      - 3100:3100
