sonar.projectName=rpe :: expressjs-template
sonar.projectKey=rpe-expressjs-template

sonar.sources=src/main
sonar.tests=src/test

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.coverage.exclusions=src/main/development.ts,src/main/server.ts